[build]
builder = "NIXPACKS"
buildCommand = "npm run railway:build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Node.js version
NODE_VERSION = "18"
# Next.js configuration
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
